# Generated by Django 5.1.4 on 2025-01-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0002_leaderboardentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('data_href', models.URLField()),
                ('image_url', models.URLField()),
            ],
        ),
    ]
