# Generated by Django 5.1.4 on 2025-01-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0003_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='data_href',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='level',
            name='image_url',
            field=models.TextField(),
        ),
    ]
