# Generated by Django 5.1.4 on 2025-01-12 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0004_alter_level_data_href_alter_level_image_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Level',
        ),
    ]
